# Laboratory work #2,  Kuralay Makhmetova, id: 26207

# Task 1

In [1]:
import pandas as pd #importing pandas library as pd
import numpy as np #importing numpy library as np
#creating the list of 3 by 3 matrixes
arr = [[2, 4, 6, 8, 10, 12, 14, 16, 18], [9, 8, 7, 6, 5, 4, 3, 2, 1]]

# convert to 3D list in-place
for i, data in enumerate(arr):
    arr[i] = [[data[0], data[1], data[2]],
               [data[3], data[4], data[5]],
               [data[6], data[7], data[8]]]

# utility for print a 3x3 matrix         
def formatrix(label, matrix):
    indent = len(label)
    return '\n'.join((label + ', '.join(map(str, matrix[0])),
                      indent*' ' + ', '.join(map(str, matrix[1])),
                      indent*' ' + ', '.join(map(str, matrix[2]))))

# print each matrix in reformatted list
for i, matrix in enumerate(arr):
    print(formatrix('array[%s]: ' % i, matrix))

array[0]: 2, 4, 6
          8, 10, 12
          14, 16, 18
array[1]: 9, 8, 7
          6, 5, 4
          3, 2, 1


In [2]:
np.multiply(arr[0],arr[1]) #multiplying this matrixes

array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

# Task 2

In [3]:
arr1 = [2, 3, 5, 7, 11] # the list of first array
arr2 = [13, 17, 19, 23, 29] # the list of second array

arr3 = np.array([arr1, arr2]) # the formation of 2 by 2 array

print(arr3) # print the formated array 

[[ 2  3  5  7 11]
 [13 17 19 23 29]]


# Task 3

In [4]:
arr = [[32,64,128], [256,512,1024]] #the list of array containing the first six powers of 2 beginning with 20
arr = np.array(arr) #the the formation of array
print (arr.reshape((2, 3))) # print of the 2 by 3 array 

[[  32   64  128]
 [ 256  512 1024]]


In [5]:
print( arr.flatten() ) # the method of flatten
print ( arr.ravel() ) # the method of ravel

[  32   64  128  256  512 1024]
[  32   64  128  256  512 1024]


# Task 4

In [6]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] #creating an array containing the values 1–15
arr1 = np.reshape(arr, (3, 5)) # # print of the 3 by 5 array 
print(arr1) # print of the 3 by 5 array 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [7]:
#A Select row 2
print(arr1[1,:])

[ 6  7  8  9 10]


In [8]:
#B Select column 5
print(arr1[:,4])

[ 5 10 15]


In [9]:
#C Select rows 0 and 1
print(arr1[0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
#D Select columns 2–4
print(arr1[:,[1,2,3]])

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [11]:
#E Select the element that is in row 1 and column 4
print(arr1[0][3])

4


In [12]:
#F Select all elements from rows 1 and 2 that are in columns 0, 2 and
print(arr1[:2,[0,2,3]])

[[1 3 4]
 [6 8 9]]


# Task 5

In [13]:
arr1 = np.array([[0, 1], [2, 3]]) #the the formation of first array
arr2 = np.array([[4, 5], [6, 7]]) #the the formation of second array

#A Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2
arr3 = np.vstack((arr1.flatten(), arr2.flatten()))
print(arr3)

[[0 1 2 3]
 [4 5 6 7]]


In [14]:
#B Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1
arr4 = np.hstack((arr1, arr2))
print(arr4)

[[0 1 4 5]
 [2 3 6 7]]


In [15]:
#C Use vertical stacking with two copies of array4 to create a 4-by-4 array5.
arr5 = np.vstack((arr4, arr4))
print(arr5)

[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]


In [16]:
#D Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.
arr6 = np.hstack((arr3, arr3))
print(arr6)

[[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]]


# Task 6 

In [17]:
# A Createa Series from the list [7,11,13,17]
series = pd.Series([7, 11, 13, 17])
print(series)

0     7
1    11
2    13
3    17
dtype: int64


In [18]:
# B Create a Series with five elements that are all 100.0
series1 = pd.Series([100.0, 100.0, 100.0, 100.0, 100.0])
print(series1)

0    100.0
1    100.0
2    100.0
3    100.0
4    100.0
dtype: float64


In [19]:
#D Create a Series called temperatures of the floating-point values 98.6,98.9,100.2 and 97.9. Using the index keyword argument, specify the custom indices 'Julie','Charlie', 'Sam' and 'Andrea'
temperatures = pd.Series(['98.6', '98.9', '100.2', '97.9'])
series = ['Julie','Charlie', 'Sam', 'Andrea']
pd.Series(series, index=temperatures)

98.6       Julie
98.9     Charlie
100.2        Sam
97.9      Andrea
dtype: object

In [20]:
#E Form a dictionary from the names and values in Part (d), then use it to initialize a Series
series2 = pd.Series()
print(series2)

Series([], dtype: float64)


<ipython-input-20-dd8aa6008447>:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  series2 = pd.Series()


# Task 7 


In [21]:
#A Create a DataFrame named temperatures from a dictionary of three temperature readings each for 'Maxine', 'James' and 'Amanda'
temperatures1 = pd.Series(['Maxine', 'James', 'Amanda'])
print(temperatures)

0     98.6
1     98.9
2    100.2
3     97.9
dtype: object


In [22]:
#B Recreate the DataFrame temperatures in Part (a) with custom indices using the index keyword argument and a list containing 'Morning', 'Afternoon' and 'Evening'
series3 = ['Morning', 'Afternoon', 'Evening']
pd.Series(series3, index=temperatures1)

Maxine      Morning
James     Afternoon
Amanda      Evening
dtype: object

In [23]:
#C Select from temperatures the column of temperature readings for 'Maxine'
temperatures1[0]

'Maxine'

In [24]:
#D Select from temperatures the row of 'Morning' temperature readings
series3[0]

'Morning'

In [25]:
#E Select from temperatures the rows for 'Morning' and 'Evening' temperature readings.
print(series3[0])
print(series3[2])

Morning
Evening


In [26]:
#F Select from temperatures the columns of temperature readings for 'Amanda' and 'Maxine'
print(temperatures1[0])
print(temperatures1[2])

Maxine
Amanda


In [27]:
#G Select from temperatures the elements for 'Amanda' and 'Maxine' in the 'Morning' and 'Afternoon'
print(series3[0])
print(series3[2])
print(temperatures1[0])
print(temperatures1[2])

Morning
Evening
Maxine
Amanda


In [28]:
#H Use the describe method to produce temperatures’ descriptive statistics
temperatures1.describe()

count          3
unique         3
top       Maxine
freq           1
dtype: object

In [29]:
#I Transpose temperatures
np.transpose(temperatures1)

0    Maxine
1     James
2    Amanda
dtype: object

In [30]:
#J Sort temperatures so that its column names are in alphabetical order
sorted_list = sorted(temperatures1)
print(sorted_list)

['Amanda', 'James', 'Maxine']
